#!/bin/bash
# Start the Tongfly Studio frontend with the built-in UDP output bridge.
# The browser talks to Vite over HTTP; Vite forwards mode/content JSON as UDP.

set -e

cd "$(dirname "$0")"

TONGFLY_MODE_UDP_HOST="${TONGFLY_MODE_UDP_HOST:-127.0.0.1}"
TONGFLY_MODE_UDP_PORT="${TONGFLY_MODE_UDP_PORT:-9100}"
TONGFLY_CONTENT_UDP_HOST="${TONGFLY_CONTENT_UDP_HOST:-127.0.0.1}"
TONGFLY_CONTENT_UDP_PORT="${TONGFLY_CONTENT_UDP_PORT:-9200}"
TONGFLY_OUTPUT_UDP_HOST="${TONGFLY_OUTPUT_UDP_HOST:-127.0.0.1}"
TONGFLY_OUTPUT_UDP_PORT="${TONGFLY_OUTPUT_UDP_PORT:-9300}"
TONGFLY_OUTPUT_IMAGE_ROOT="${TONGFLY_OUTPUT_IMAGE_ROOT:-/home/elf}"

echo "Starting frontend"
echo "Mode UDP target: ${TONGFLY_MODE_UDP_HOST}:${TONGFLY_MODE_UDP_PORT}"
echo "Content UDP target: ${TONGFLY_CONTENT_UDP_HOST}:${TONGFLY_CONTENT_UDP_PORT}"
echo "Output UDP listen: ${TONGFLY_OUTPUT_UDP_HOST}:${TONGFLY_OUTPUT_UDP_PORT}"
echo "Output image root: ${TONGFLY_OUTPUT_IMAGE_ROOT}"
npm run dev -- --host
